name: CI Arca Scraper

on:
  push:
    branches: [ main ]  # Roda sempre que você der push na branch principal
  schedule:
    # Agendamento: 03:00 UTC é 00:00 AM no horário de Brasília (UTC-3)
    # Roda toda madrugada de Domingo para Segunda
    - cron: '0 3 * * 1'
  workflow_dispatch:    # Permite que você rode o bot manualmente pelo site do GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        # Instala as ferramentas de teste e as libs necessárias para o main.py
        pip install flake8 requests pymongo beautifulsoup4

    - name: Verificar erros de sintaxe (Lint)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Executar Scraper (O Maestro)
      env:
        # Mapeamento das chaves secretas configuradas no GitHub
        MONGO_URI: ${{ secrets.MONGO_URI }}
        IMPERIAL_TOKEN: ${{ secrets.API_AUTHORIZATION_TOKEN }}
        OUTRA_CHAVE: ${{ secrets.OUTRA_CHAVE }}
        PYTHONPATH: .
      run: |
        python main.py

    - name: Finalizado
      run: echo "✅ Coleta e análise concluídas com sucesso!"
